config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/', to: 'cocktails#index'

  resources :cocktails do
    resources :doses, only: [:new, :create]
  end

  resources :doses, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, :through => :doses

  validates :name, uniqueness: true, presence: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  validates :description, :cocktail_id, :ingredient_id, presence: true
  validates :cocktail, uniqueness: { scope: :ingredient }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses

  validates :name, uniqueness: true, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController

  def index
    @cocktails = Cocktail.all
  end

  def show
    set_cocktail
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)

    if @cocktail.save
      redirect_to @cocktail, notice: 'cocktail was successfully created.'
    else
      render :new
    end
  end

  def edit
    set_cocktail
  end

  def update
    set_cocktail
    @cocktail.update(cocktail_params)
    redirect_to cocktail_path(@cocktail)
  end

  def destroy
    set_cocktail
  end

  private

  def set_cocktail
    @cocktail = Cocktail.find(params[:id])
  end

  def cocktail_params
    params.require(:cocktail).permit(:name)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController

  def new
    @dose = Dose.new
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def create
    @dose = Dose.new(dose_params)
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose.cocktail = @cocktail

    if @dose.save
      redirect_to cocktail_path(@cocktail), notice: 'dose was successfully added.'
    else
      render :new
    end
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/cocktails/_form.html.erb
<%= simple_form_for(@cocktail) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/cocktails/_forms.html.erb
<%= simple_form_for(@cocktail, @dose) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <% @cocktail.dose.each do |dose| %>
    <%= f.input :address %>
    <%= f.input :description %>
    <%= f.input :stars %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/cocktails/edit.html.erb
<div class="container">
  <h1><%= @cocktail.name %></h1>
  <%= render "form" %>
</div>

app/views/cocktails/index.html.erb
<div class="container">
  <h1>Your cocktail list</h1>

  <br>

  <ul>
    <% @cocktails.each do |cocktail| %>
      <li>
        <%= link_to cocktail.name, cocktail_path(cocktail) %>
      </li>
    <% end %>
  </ul>

  <br>

  <%= link_to 'New cocktail', new_cocktail_path %>
</div>

app/views/cocktails/new.html.erb
<div class="container">

</div>

app/views/cocktails/show.html.erb
<div class="container">

  <%= link_to 'Home', cocktails_path %>

  <br>

  <div class="banner-title">
    <h1><%= @cocktail.name %></h1>
    <%= link_to(edit_cocktail_path(@cocktail), html_options = {}) do %>
      <i class="far fa-edit"></i>
    <% end %>
  </div>

  <br>

  <ol>
    <% @cocktail.doses.each do |dose| %>
      <li>
        <%= dose.ingredient.name %>
        <%= dose.description %>
      </li>
    <% end %>
  </ol>

  <br>
  <br>

  <%= link_to 'Add a new dose', new_cocktail_dose_path(@cocktail) %>

</div>

app/views/doses/_form.html.erb
<%= simple_form_for([@cocktail, @dose]) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :description %>
    <%= f.association :ingredient %>
  </div>

  <div class="form-actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/doses/new.html.erb
<div class="container">
  <h1>Add a new dose for the cocktail</h1>
  <%= render "form" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Responsiveness -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>

    <!-- app/views/layouts/application.html.erb -->

    <%= javascript_include_tag "application" %> <!-- from app/assets/javascripts/application.js -->
    <%= javascript_pack_tag "application" %>    <!-- from app/javascript/packs/application.js -->
  </body>
</html>